name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore dependencies 
      run: dotnet restore Challenge_one/Challenge_one.sln
    - name: Build
      run: dotnet build Challenge_one/Challenge_one.sln --no-restore
    - name: Test
      run: dotnet test Challenge_one/Challenge_one.sln --no-build --verbosity normal
